version: 0.0
os: linux
files:
  - sources: /
    destination: /home/ec2-user/golang-app
hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
